SELECT
    C.CART_ID,
    CASE
        WHEN SUM(P.PRICE) < C.MINIMUM_REQUIREMENT THEN 1
        ELSE 0
        END AS ABUSED
FROM COUPONS C
         JOIN CART_PRODUCTS P
              ON C.CART_ID = P.CART_ID
GROUP BY C.CART_ID, C.MINIMUM_REQUIREMENT
ORDER BY C.CART_ID;