WITH RECURSIVE generations AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL   -- 루트(부모 없는) 대장균 = 1세대

    UNION ALL

    SELECT e.ID, e.PARENT_ID, g.GENERATION + 1
    FROM ECOLI_DATA e
             JOIN generations g
                  ON e.PARENT_ID = g.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM generations g
WHERE g.ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION;