-- JOIN + GROUP BY 
SELECT FLAVOR
FROM (
    SELECT F.FLAVOR AS FLAVOR, SUM(J.TOTAL_ORDER + F.TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF F JOIN (
                        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
                        FROM JULY
                        GROUP BY FLAVOR) J
    ON F.FLAVOR = J.FLAVOR 
    GROUP BY F.FLAVOR
    ORDER BY TOTAL DESC
) T
LIMIT 3

-- UNION ALL
SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM (
        SELECT FLAVOR, TOTAL_ORDER
        FROM JULY 

        UNION ALL

        SELECT FLAVOR, TOTAL_ORDER
        FROM FIRST_HALF  
    ) F
    GROUP BY FLAVOR
    ORDER BY TOTAL DESC
) T
LIMIT 3


 